build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        tests-and-coverage:
            environment:
                php:
                    version: 7.1
            tests:
                override:
                    - phpcs-run
                    -
                        command: 'vendor/bin/phpunit'
                        coverage:
                            file: 'build/logs/clover.xml'
                            format: 'clover'
filter:
    excluded_paths:
        - 'tests/*'
