sudo: false

language: php
php:
  - 7.4

env:
  - SF_CACHE=3
  - SF_CACHE=4
  - SF_CACHE=4.3
  - SF_CACHE=5

before_script:
  - composer install --no-interaction -o
  - if [ "$SF_CACHE" = "3" ]; then composer require symfony/cache:^3.3; fi;
  - if [ "$SF_CACHE" = "4" ]; then composer require symfony/cache:">=4.0 <4.3"; fi;
  - if [ "$SF_CACHE" = "4.3" ]; then composer require symfony/cache:^4.3; fi;
  - if [ "$SF_CACHE" = "5" ]; then composer require symfony/cache:5.0; fi;

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
